#!/bin/bash

TARGET=$1
SOURCE=$2

: "${SOURCE:=ubuntu1604}"
: "${TARGET:=vm$RANDOM}"

cp -R "$HOME/vm/$SOURCE.vmwarevm/" "$HOME/vm/$TARGET.vmwarevm/"
for i in vmx vmxf vmsd plist nvram
  do mv "$HOME/vm/$TARGET.vmwarevm/$SOURCE".$i                                 \
        "$HOME/vm/$TARGET.vmwarevm/$TARGET".$i
done

echo 'uuid.action = "create"' >> "$HOME/vm/$TARGET.vmwarevm/$TARGET.vmx"
sed -i.bak "s/$SOURCE/$TARGET/g" "$HOME/vm/$TARGET.vmwarevm/$TARGET.vmx"
rm "$HOME/vm/$TARGET.vmwarevm/$TARGET.vmx.bak"
rm -r "$HOME/vm/$TARGET.vmwarevm/*.vmx.lck" 2>/dev/null

vmrun start "$HOME/vm/$TARGET.vmwarevm/$TARGET.vmx" nogui 2&>/dev/null
until ssh -o StrictHostKeyChecking=no                                          \
          -o UserKnownHostsFile=/dev/null                                      \
          $SOURCE.local exit 2>/dev/null;                                      \
          do sleep 2;
      done

ssh -o StrictHostKeyChecking=no                                                \
    -o UserKnownHostsFile=/dev/null                                            \
    $SOURCE.local                                                              \
    sudo sed -i'' "s/$SOURCE/$TARGET/" /etc/hosts                              \
    2>/dev/null

ssh -o StrictHostKeyChecking=no                                                \
    -o UserKnownHostsFile=/dev/null                                            \
    $SOURCE.local                                                              \
    sudo hostnamectl set-hostname $TARGET                                      \
    2>/dev/null

ssh -o StrictHostKeyChecking=no                                                \
    -o UserKnownHostsFile=/dev/null                                            \
    $SOURCE.local                                                              \
    sudo reboot 2>/dev/null

echo "$TARGET.local started"
