#!/bin/bash

[ "$1" == "-m" ] && { shift; MAC=$1; shift; }

TARGET="${1:-vm$RANDOM}"
SOURCE="${2:-ubuntu1604}"

TARGETDIR="$HOME/vm/$TARGET.vmwarevm"

cp -R "$HOME/vm/$SOURCE.vmwarevm/" "$TARGETDIR/"
for i in vmx vmxf vmsd plist nvram
  do mv "$TARGETDIR/$SOURCE".$i                                                \
        "$TARGETDIR/$TARGET".$i
done

echo 'uuid.action = "create"' >> "$TARGETDIR/$TARGET.vmx"

sed -i.bak                                                                     \
    "s/$SOURCE/$TARGET/g"                                                      \
    "$TARGETDIR/$TARGET.vmx"

if [ -n "$MAC" ]; then
  sed -i.bak                                                                   \
      '/ethernet0.generatedAddress/d'                                          \
      "$TARGETDIR/$TARGET.vmx"
  sed -i.bak                                                                   \
      's/ethernet0.addressType.*/ethernet0.addressType = "static"/'            \
      "$TARGETDIR/$TARGET.vmx"
  echo "ethernet0.address = \"$MAC\""                                          |
      tee -a "$TARGETDIR/$TARGET.vmx"                                          \
      &>/dev/null
fi

rm -r "$TARGETDIR/$SOURCE*" &>/dev/null
rm -r "$TARGETDIR/"*.{log,bak} &>/dev/null

vmrun start "$TARGETDIR/$TARGET.vmx" nogui &>/dev/null
until ssh -o StrictHostKeyChecking=no                                          \
          -o UserKnownHostsFile=/dev/null                                      \
          $SOURCE.local exit &>/dev/null;                                      \
          do sleep 2;
      done

ssh -o StrictHostKeyChecking=no                                                \
    -o UserKnownHostsFile=/dev/null                                            \
    $SOURCE.local                                                              \
    sudo sed -i'' "s/$SOURCE/$TARGET/" /etc/hosts                              \
    &>/dev/null

ssh -o StrictHostKeyChecking=no                                                \
    -o UserKnownHostsFile=/dev/null                                            \
    $SOURCE.local                                                              \
    sudo hostnamectl set-hostname $TARGET                                      \
    &>/dev/null

ssh -o StrictHostKeyChecking=no                                                \
    -o UserKnownHostsFile=/dev/null                                            \
    $SOURCE.local                                                              \
    sudo reboot                                                                \
    &>/dev/null

echo "$TARGET.local started"
