#!/bin/bash

VMROOT=$HOME'/Documents/Virtual Machines.localized'

if [ -z "$1" ];
  then
    echo 'VM name must be provided'
    exit 0
  else
    NAME=$1
fi

echo "Stopping $NAME"
vmrun stop "$VMROOT/$NAME.vmwarevm/$NAME.vmx" soft nogui
