#!/bin/bash

VMROOT=$HOME'/Documents/Virtual Machines.localized'

if [ -z "$1" ];
  then
    echo 'VM name must be provided'
    exit 0
  else
    NAME=$1
  fi

echo "Starting $NAME"
vmrun start "$VMROOT/$NAME.vmwarevm/$NAME.vmx" nogui 2&>/dev/null
